# Generated by Django 4.1.1 on 2022-09-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='filename',
        ),
    ]
